package orm.model;

import java.math.BigDecimal;

public class Product {

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column product.productID
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column product.productCode
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    private String productcode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column product.name
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column product.quantity
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column product.price
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column product.productID
     *
     * @return the value of product.productID
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column product.productID
     *
     * @param productid the value for product.productID
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column product.productCode
     *
     * @return the value of product.productCode
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column product.productCode
     *
     * @param productcode the value for product.productCode
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column product.quantity
     *
     * @return the value of product.quantity
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column product.quantity
     *
     * @param quantity the value for product.quantity
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sun Jan 31 22:17:46 SGT 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return "Product [name=" + name + ", price=" + price + ", productcode=" + productcode + ", productid="
                + productid + ", quantity=" + quantity + "]";
    }

    public Product(String productcode, String name, Integer quantity, double price) {
        this.productid = null;
        this.productcode = productcode;
        this.name = name;
        this.quantity = quantity;
        this.price = BigDecimal.valueOf(price);
    }

    public Product() {
    }

}